Dou et al. (2020) model

Agora em Julia versão 1.5.3

This script simulates the model

We will use the results of the estimation using W=Identity and using fixed skills the same as Dou et al

In [2]:
using LinearAlgebra, Statistics

# using Distributions, Expectations, NLsolve, Roots, Random, Plots, Parameters


using DataFrames
using BenchmarkTools



In [3]:
using NBInclude
@nbinclude("solve_model_cf.ipynb")

#importou a função solve_tree

In [4]:
# g = [0.71, 20.3, 0.22, 0.01], s = [28.0, 36.0, 2.4], fc = 0.17250006355753533

In [5]:
#Vh/D, L/D, Dj/D
data = [1.32, 0.32, 0.78]; 

#ρ, β, c0, λj
game_parameters = [0.71, 20.3, 0.22, 0.01];

#counterfactual parameters####
D = Float64(1.0)

#simulation of baseline model, tsym=1
tsym = Int64(1)
dip = Float64(0.00)

additional_cost = dip * D
ac_s = additional_cost
ac_j = additional_cost

counterfactual_parameters = [tsym, additional_cost, ac_s, ac_j];

In [6]:
s_W, j_W, Pst_array, Pjt_array, Ds, Dj = solve_tree(data, game_parameters, counterfactual_parameters);

  4.247617 seconds (44.49 M allocations: 921.645 MiB, 6.05% gc time)
  5.505885 seconds (43.22 M allocations: 858.002 MiB, 1.87% gc time)
  7.182635 seconds (43.22 M allocations: 858.002 MiB, 1.25% gc time)
  7.902050 seconds (43.22 M allocations: 858.002 MiB, 1.16% gc time)
  8.089146 seconds (43.22 M allocations: 858.002 MiB, 1.17% gc time)
  8.807028 seconds (40.16 M allocations: 811.310 MiB, 1.02% gc time)
 42.598126 seconds (257.57 M allocations: 5.046 GiB, 1.70% gc time)


Simulation parameters

In [7]:
#θs0, θj0, μ
simulation_parameters = [28.0, 36.0, 2.4];

### Criando funções para simular o jogo

In [8]:
θs0, θj0, μ = simulation_parameters;
θs0 = Int64(θs0);
θj0 = Int64(θj0);

#parameters to some functions that are similar as the ones in solve_model

c0 = game_parameters[3];
c1 = Float64(0.0015);

ρ = game_parameters[1];
λj = game_parameters[4];


Vmax = data[1];
L = data[2];
Dj = data[3];

D = Float64(1.0)
Ds = D - Dj;


In [9]:
#counterfactual parameters
tsym = counterfactual_parameters[1]
additional_cost = counterfactual_parameters[2]
ac_s = counterfactual_parameters[3]
ac_j = counterfactual_parameters[4];

In [10]:
#cost function
function Ct(t)
    #cost at period t=0(index1) is 0
    if(t <= 1)
        return 0
    else
        return c0  + c1 * (t-1) #test to make index==1 be t==0
    end
end



#liquidation payoffs

function s_L(t, additional_cost=ac_s, Ds=Ds)
    S_L = min(L - Ct(t) - additional_cost, Ds)
    return max(S_L, zero(0.0))
end

function j_L(t, additional_cost=ac_j, Dj=Dj)
    J_L = min(L - Ct(t) - additional_cost - s_L(t), Dj)
    return max(J_L, zero(0.0))
end


function proposal(Pkt_array, t, hkt, lmt)
    
    #pkt array será sempre do propositor, quem responder às propostas apenas olhará o seu valor de continuação
    
    return policy, payoff_prop, payment, lm_next = Pkt_array[t, hkt, lmt, [end,end-1, 1, 2]]
    
end
    

#maximum value of reorganization each period
function Vt(Vmax, ρ, t, additional_cost)

    if(t <=1)
        return Vmax - additional_cost
    else
        #(t-2) instead of (t-1) because we shifted the indexes in the game so as to include t==0 at index==1
        return ρ^(t-2) * Vmax - additional_cost
    end


end

# answer_liq
function answer_liq(m_L, t, hm_next, payoff_prop, additional_cost, ac_s, ac_j)
    
    liq = (m_L(t), Vt(Vmax, ρ, t, additional_cost) * hm_next/100 - Ct(t) - payoff_prop)
    
    payoff_liq, answer = findmax(liq)
    
    return payoff_liq, answer
end

function answer_reorg(payment, Cont_val, t, hm_next, lm_next, lk_next)
    
    reorg_value = (payment, Cont_val[t+1, hm_next, lm_next, lk_next])

    payoff_reorg, answer = findmax(reorg_value)
    
    return payoff_reorg, answer
end

function update_beliefs(propositor, hk_next, hm_next, lk_next, lm_next, t, tsym)
    
    if(t<=tsym)
        
        #t <= tsym, there is symmetric information
        
         if(propositor=="s")
            hst = hk_next
            lst = hk_next

            hjt = hm_next
            ljt = hm_next

        else
            hst = hm_next
            lst = hm_next

            hjt = hk_next
            ljt = hk_next
        end
        
    else
        
        #t > tsym, there is asymmetric information


        if(propositor=="s")
            hst = hk_next
            lst = lk_next

            hjt = hm_next
            ljt = lm_next

        else
            hst = hm_next
            lst = lm_next

            hjt = hk_next
            ljt = lk_next
        end
    end

    
    return hst, lst, hjt, ljt
end

        

update_beliefs (generic function with 1 method)

In [11]:
#código para tirar um draw da beta

function draw_beta(hkt, β=game_parameters[2], grid=100)

    u = rand()

    if(hkt == 100)
        
        return 100

    else
        
        x = 1.0 - exp(1.0/β * (log(1.0 - u) + β * log(1.0 - hkt/grid)))
        x = round(x * 100, digits=0)
#         return Int64(x * 100) #to convert in an integer
        return Int64(x)
        
    end
end

        

# @code_warntype draw_beta(10)



draw_beta (generic function with 3 methods)

In [12]:
function choose_parameters(propositor, hst, lst, hjt, ljt)
    
    if(propositor=="s")
        
        Pkt_array = Pst_array
        Cont_val = j_W
        prop_index = 1
        respondent_index = 2 #índice de j, para organizar o payoff
        m_L = j_L

        hkt = hst
        lkt = lst
        
        hmt = hjt
        lmt = ljt


        lk_next = hkt

        hk_next = draw_beta(hkt)
        hm_next = draw_beta(hmt)
        
    elseif(propositor=="j")
        Pkt_array = Pjt_array
        Cont_val = s_W
        prop_index = 2
        respondent_index = 1
        m_L = s_L

        hkt = hjt
        lkt = ljt
        
        hmt = hst
        lmt = lst


        lk_next = hkt


        hk_next = draw_beta(hkt)
        hm_next = draw_beta(hmt)

    else
        
        println("error: propositor not valid")
        
    end
    
    return Pkt_array, Cont_val, prop_index, respondent_index, m_L, hkt, lkt, hmt, lmt, lk_next, hk_next, hm_next
end




#test
Hs0 = 30
Hj0 = 28


hst = Hs0
hjt = Hj0

#assumindo que lower bounds nos períodos iniciais são as próprias habilidades iniciais
lst = hst
ljt = hjt




choose_parameters("s", hst, lst, hjt, ljt);
    
    

In [13]:
function simulate_game(Hs0, Hj0, μ, λj, counterfactual_parameters, s_W=s_W, j_W=j_W, Pst_array=Pst_array, Pjt_array=Pjt_array, t=1, grid=100)
    
    hst = Hs0
    hjt = Hj0

    #assumindo que lower bounds nos períodos iniciais são as próprias habilidades iniciais
    lst = hst
    ljt = hjt
    
    result = zeros(5);
    
    #number of observed proposals
    observed_proposals = 0.0
    
    
    #recovering "T+1" from s_W 
    T = size(s_W,1)
    
    
    #counterfactual parameters
    tsym = counterfactual_parameters[1]
    additional_cost = counterfactual_parameters[2]
    ac_s = counterfactual_parameters[3]
    ac_j = counterfactual_parameters[4];
    
    
    
    while(result[1]==0.0 && t < T)
        
        
        u = rand()

        if(u < λj)
            propositor = "j"

        else
            propositor = "s"

        end

        
        #setting the default variables according to the propositor
        Pkt_array, Cont_val, prop_index, respondent_index, m_L, hkt, lkt, hmt, lmt, lk_next, hk_next, hm_next = choose_parameters(propositor, hst, lst, hjt, ljt)
        
        
        #proposal ####
        policy, payoff_prop, payment, lm_next = proposal(Pkt_array, t, hkt, lmt)

        #lm_next is the update of the adversary's lower bound
        if(lm_next>=grid+1 || policy!= 3.0) #para evitar update de lowerbound quando proponente não propõe reorg
            lm_next = lmt
        else
            lm_next = Int64(lm_next)
        end
        
        
        
        if(policy==3.0)
            
            observed_proposals += 1.0
    
            payoff_respondent, answer = answer_reorg(payment, Cont_val, t, hm_next, lm_next, lk_next)


            if(answer==1.0)

                result[prop_index] = payoff_prop
                result[respondent_index] = payoff_respondent
                result[3] = 3.0
                result[4] = t
                result[5] = observed_proposals

            else
                
                t+=1

                hst, lst, hjt, ljt = update_beliefs(propositor, hk_next, hm_next, lk_next, lm_next, t, tsym)
            end

        elseif(policy==2.0)
            
            t+=1
            
            hst, lst, hjt, ljt = update_beliefs(propositor, hk_next, hm_next, lk_next, lm_next, t, tsym)
            
            

        else      
            #(policy==1.0)
            
            observed_proposals += 1.0

            payoff_respondent, answer = answer_liq(m_L, t, hm_next, payoff_prop, additional_cost, ac_s, ac_j)

            if(answer==1.0)

                result[prop_index] = payoff_prop
                result[respondent_index] = payoff_respondent
                result[3] = 1.0
                result[4] = t
                result[5] = observed_proposals

            else

                result[prop_index] = payoff_prop
                result[respondent_index] = payoff_respondent
                result[3] = 3.0
                result[4] = t
                result[5] = observed_proposals


            end
        end


        if(t==T)
            
            result[1] = s_W[T, 1, 1, 1]#todos os valores finais de S são iguais, então acessarei o índice 1
            result[2] = j_W[T, 1, 1, 1]
            result[3] = 1.0
            result[4] = t
            result[5] = max(observed_proposals, 1.0) #to avoid observed_proposals==0.0
            
        end
        




    end
    
    
    return result
end

        
        
#precisa colocar uma condição IF aqui para caso o jogo vá até o último período?
    

simulate_game (generic function with 7 methods)

In [14]:
# simulate_game(θs0, θj0, μ, λj, s_W, j_W, Pst_array, Pjt_array)

In [15]:
function loop_simulations(S, N, θs0, θj0, μ, λj, counterfactual_parameters, s_W=s_W, j_W=j_W, Pst_array=Pst_array, Pjt_array=Pjt_array)
    
    #S is the number of simulations
    #N is the number of observations
    
    #no futuro os argumentos podem ser arrays de arrays, assim ele faz o loop para cada cluster
    
    Results = zeros(S, N, 7)

    #últimas entradas de Results são os valores das dívidas
    Results[:,:, end-1] .= Dj
    Results[:,:, end] .= Ds


    for s in 1:S
        for n in 1:N
            Results[s,n,1:5] .= simulate_game(θs0, θj0, μ, λj, counterfactual_parameters)
        end
    end

    return Results
    
end

    
# loop_simulations(40, 75, θs0, θj0, μ, λj);

In [16]:
function simulate_moments(S, N, θs0, θj0, μ, λj, counterfactual_parameters, s_W=s_W, j_W=j_W, Pst_array=Pst_array, Pjt_array=Pjt_array)
    
    
    Results = loop_simulations(S, N, θs0, θj0, μ, λj, counterfactual_parameters)
    
    
    Moments = zeros(S, 8)
    
    
    for s in 1:S

            DF = DataFrame()
            DF.payoff_s = Results[s,:,1];
            DF.payoff_j = Results[s,:,2];
            DF.out = Results[s,:,3];
            DF.t = Results[s,:,4];
            DF.observed_proposals = Results[s,:,5];
            DF.Dj = Results[s,:,6];
            DF.Ds = Results[s,:,7];


            DF.outcome = ifelse.(DF.out .==3.0, "R", "L");


            #desfazendo o deslocamento no índice de t
            DF.t = DF.t .- 1.0;

            # DF.incourt = ifelse.(DF.t .> 0.0, "incourt", "precourt");

            INCOURT = filter(DF -> DF.t .> 0.0, DF);
            PRECOURT = filter(DF -> DF.t .<= 0.0, DF);

            PRECOURT_REORG = filter(PRECOURT -> PRECOURT.outcome .== "R", PRECOURT)
            INCOURT_REORG = filter(INCOURT -> INCOURT.outcome .== "R", INCOURT)

            #cálculo dos momentos
            #1. avg log number of months between observed proposals incourt

            mm1 = INCOURT
            mm1 = log.(mm1.t .* μ ./ mm1.observed_proposals)
            mm1 = mean(mm1)

            #2. fraction reorganized given that the case went into court

            mm2 = INCOURT
            mm2 = size(filter(mm2 -> mm2.outcome .== "R", mm2),1)/ size(mm2,1)

            #3. ln duration of court cases in months

            mm3 = INCOURT
            mm3 = filter(mm3 -> mm3.t .> 0.0, mm3) #removendo os casos 0 para não poluir a média
            mm3.t = mm3.t .* μ
            mm3 = mean(log.(mm3.t)) #log here uses exp as base, so it's the same as ln

            #4. fraction of cases incourt
            mm4 = size(INCOURT,1) / size(DF, 1)

            #5. avg recovery rate for senior given precourt REORGANIZATION

            #aqui nós temos Ds, então é mais fácil. Preciso automatizar isso no código quando for tudo escalado

            mm5 = PRECOURT_REORG
            mm5.R_s = mm5.payoff_s ./ mm5.Ds
            mm5 = mean(mm5.R_s)

            #if there are no precourt cases, it will return zero
            if(isnan(mm5))
                mm5 = zero(0.0)
            end


            #6. avg recovery rate for junior given precourt REORGANIZATION

            #aqui nós temos Ds, então é mais fácil. Preciso automatizar isso no código quando for tudo escalado

            mm6 = PRECOURT_REORG
            mm6.R_j = mm6.payoff_j ./ mm6.Dj
            mm6 = mean(mm6.R_j)

            #if there are no precourt cases, it will return zero
            if(isnan(mm6))
                mm6 = zero(0.0)
            end


            #7. junior avg fraction gain given incourt REORGANIZATION

            mm7 = INCOURT_REORG
            mm7 = mean(mm7.payoff_j ./ (mm7.payoff_j .+ mm7.payoff_s )) 

            #8. total recovery rate given incourt REORGANIZATION

            mm8 = INCOURT_REORG
            mm8 = mean( mm8.payoff_s .+ mm8.payoff_j)



            Moments[s,:] .= [mm1, mm2, mm3, mm4, mm5, mm6, mm7, mm8]

            #if there are no INCOURT or no PRECOURT cases, it will return NaN
            #thus, we replace it by zero
            Moments[s,:] .= replace!(Moments[s,:], NaN=> zero(0.0))

        end
    return vec(mean(Moments, dims=1))
end

simulate_moments (generic function with 5 methods)

In [17]:
using Random

In [29]:
#test
S = 40
N = 66


simulated_moments = simulate_moments(S, N, θs0, θj0, μ, λj, counterfactual_parameters)

8-element Array{Float64,1}:
 0.40532370872339313
 0.996875
 1.4422462437526702
 0.08181818181818182
 1.530656714989828
 0.08547643388204507
 0.38971212955466455
 0.22295210658877096

Comparing with the actual data moments

In [19]:
#data_moments
data_moments = [0.728, 0.843, 2.76, 0.969, 0.6235, 0.5569, 0.773, 0.497];

In [20]:
function error_vector(data_moments, simulated_moments)
    #two arrays with the data moments and the simulated moments
    
# #     return (simulated_moments .- data_moments) ./ data_moments
#     
    return (simulated_moments .- data_moments)
    
end

error_vector (generic function with 1 method)

Derivative of moments w.r.t. parameters

In [21]:
game_parameters

4-element Array{Float64,1}:
  0.71
 20.3
  0.22
  0.01

In [22]:
simulation_parameters

3-element Array{Float64,1}:
 28.0
 36.0
  2.4

In [30]:
#calculando a derivada em relação a ρ

function derivative_moments(S, N, game_parameters, simulation_parameters, counterfactual_parameters, simulated_moments)
    
    
    P = size(game_parameters,1)+size(simulation_parameters,1)
    M = size(simulated_moments,1)
    D = zeros(M, P)
    
    estimated_game_parameters = game_parameters
    estimated_simulation_parameters = simulation_parameters
    
    #delta for each parameter
    #approximately 1% or the lowest decimal point
    #[game_parameters, simulation_parameters]
    delta = [0.01, 0.2, 0.002, 0.01, 1.0, 1.0, 0.02]
    
    for i in 1:P
        if(i<=size(game_parameters,1))
            game_parameters = copy(estimated_game_parameters)
            
            game_parameters[i] = game_parameters[i] + delta[i]
            
        else
            simulation_parameters = copy(estimated_simulation_parameters)
            simulation_parameters[i-size(game_parameters,1)] = simulation_parameters[i-size(game_parameters,1)] + delta[i]
            
            
        end
        
        println("parameter ",i, game_parameters, simulation_parameters)
        
        θs0, θj0, μ = simulation_parameters;
        θs0 = Int64(round(θs0, digits=0));
        θj0 = Int64(round(θj0, digits=0));

        λj = game_parameters[4];

        s_W, j_W, Pst_array, Pjt_array, Ds, Dj = solve_tree(data, game_parameters, counterfactual_parameters);
        new_simulated_moments = simulate_moments(S, N, θs0, θj0, μ, λj, counterfactual_parameters)
        
        D[:, i] = new_simulated_moments - simulated_moments
        
    end
    
    
    
    return D
    
end


derivative_moments (generic function with 1 method)

In [31]:
Derivative = derivative_moments(S, N, game_parameters, simulation_parameters, counterfactual_parameters, simulated_moments)

parameter 1[0.72, 20.3, 0.22, 0.01][28.0, 36.0, 2.4]
  3.840896 seconds (43.22 M allocations: 858.002 MiB, 2.98% gc time)
  6.158048 seconds (43.22 M allocations: 858.002 MiB, 1.97% gc time)
  7.519047 seconds (43.22 M allocations: 858.002 MiB, 1.65% gc time)
  8.294458 seconds (43.22 M allocations: 858.002 MiB, 1.64% gc time)
  8.777750 seconds (43.22 M allocations: 858.002 MiB, 1.50% gc time)
  9.780175 seconds (40.16 M allocations: 811.310 MiB, 1.38% gc time)
 44.798771 seconds (256.26 M allocations: 4.982 GiB, 1.70% gc time)
parameter 2[0.71, 20.5, 0.22, 0.01][28.0, 36.0, 2.4]
  4.600692 seconds (43.22 M allocations: 858.002 MiB, 7.93% gc time)
  6.189032 seconds (43.22 M allocations: 858.002 MiB, 1.75% gc time)
  7.153485 seconds (43.22 M allocations: 858.002 MiB, 1.63% gc time)
  7.888047 seconds (43.22 M allocations: 858.002 MiB, 1.25% gc time)
  8.171658 seconds (43.22 M allocations: 858.002 MiB, 1.43% gc time)
  8.653603 seconds (40.16 M allocations: 811.310 MiB, 1.11% gc time

8×7 Array{Float64,2}:
 -0.0530333    0.00858154   -0.00846483   …  -0.0288303   -0.00421049
  0.003125     0.003125      0.003125        -0.021875     0.003125
 -0.141024     0.0207844    -0.0235942       -0.0857328   -0.0232764
 -0.00492424  -0.00113636    0.00606061       0.00833333  -0.00378788
 -0.00123999  -0.00104348   -0.000990792     -0.0245883   -0.0045782
  0.00062555   0.000526417   0.000499834  …   0.00306823   0.00230961
 -0.0125431    0.0168044    -0.0311846       -0.00957235  -0.0281686
  0.0056955   -0.00920194   -0.00367836       9.44292e-6   0.000968279

In [32]:
Derivative[2,:]

7-element Array{Float64,1}:
  0.0031250000000000444
  0.0031250000000000444
  0.0031250000000000444
  0.0031250000000000444
  0.0031250000000000444
 -0.021874999999999978
  0.0031250000000000444