Dou et al. (2020) model

Agora em Julia versão 1.5.3

This script simulates the model

We will use the results of the estimation using W=Identity

In [1]:
using LinearAlgebra, Statistics

# using Distributions, Expectations, NLsolve, Roots, Random, Plots, Parameters


using DataFrames
using BenchmarkTools



In [2]:
using NBInclude
@nbinclude("solve_model_cf.ipynb")

#importou a função solve_tree

In [3]:
#Vh/D, L/D, Dj/D
data = [1.32, 0.32, 0.78]; 

#ρ, β, c0, λj
game_parameters = [0.52, 22.59, 0.2, 0.01];

#counterfactual parameters####
D = Float64(1.0)

#simulation of baseline model, tsym=1
tsym = Int64(1)
dip = Float64(0.00)

additional_cost = dip * D
ac_s = additional_cost
ac_j = additional_cost

counterfactual_parameters = [tsym, additional_cost, ac_s, ac_j];

In [4]:
s_W, j_W, Pst_array, Pjt_array, Ds, Dj = solve_tree(data, game_parameters, counterfactual_parameters);

  5.374993 seconds (44.49 M allocations: 921.648 MiB, 5.39% gc time)
  8.088032 seconds (43.22 M allocations: 858.002 MiB, 1.04% gc time)
  9.861009 seconds (43.22 M allocations: 858.002 MiB, 0.81% gc time)
  9.313095 seconds (40.16 M allocations: 811.310 MiB, 0.77% gc time)
 33.090234 seconds (171.13 M allocations: 3.370 GiB, 1.59% gc time)


Simulation parameters

In [5]:
#θs0, θj0, μ
simulation_parameters = [45, 99, 3.11];

### Criando funções para simular o jogo

In [6]:
θs0, θj0, μ = simulation_parameters;
θs0 = Int64(θs0);
θj0 = Int64(θj0);

#parameters to some functions that are similar as the ones in solve_model

c0 = game_parameters[3];
c1 = Float64(0.0015);

ρ = game_parameters[1];
λj = game_parameters[4];


Vmax = data[1];
L = data[2];
Dj = data[3];

D = Float64(1.0)
Ds = D - Dj;


In [7]:
#counterfactual parameters
tsym = counterfactual_parameters[1]
additional_cost = counterfactual_parameters[2]
ac_s = counterfactual_parameters[3]
ac_j = counterfactual_parameters[4];

In [8]:
#cost function
function Ct(t)
    #cost at period t=0(index1) is 0
    if(t <= 1)
        return 0
    else
        return c0 * D + c1 * (t-1) * D #test to make index==1 be t==0
    end
end



#liquidation payoffs

function s_L(t, additional_cost=ac_s, Ds=Ds)
    S_L = min(L - Ct(t) - additional_cost, Ds)
    return max(S_L, zero(0.0))
end

function j_L(t, additional_cost=ac_j, Dj=Dj)
    J_L = min(L - Ct(t) - additional_cost - s_L(t), Dj)
    return max(J_L, zero(0.0))
end


function proposal(Pkt_array, t, hkt, lmt)
    
    #pkt array será sempre do propositor, quem responder às propostas apenas olhará o seu valor de continuação
    
    return policy, payoff_prop, payment, lm_next = Pkt_array[t, hkt, lmt, [end,end-1, 1, 2]]
    
end
    

#maximum value of reorganization each period
function Vt(Vmax, ρ, t, additional_cost)

    if(t <=1)
        return Vmax - additional_cost
    else
        #(t-2) instead of (t-1) because we shifted the indexes in the game so as to include t==0 at index==1
        return ρ^(t-2) * Vmax - additional_cost
    end


end

# answer_liq
function answer_liq(m_L, t, hm_next, payoff_prop, additional_cost, ac_s, ac_j)
    
    liq = (m_L(t), Vt(Vmax, ρ, t, additional_cost) * hm_next/100 - payoff_prop)
    
    payoff_liq, answer = findmax(liq)
    
    return payoff_liq, answer
end

function answer_reorg(payment, Cont_val, t, hm_next, lm_next, lk_next)
    
    reorg_value = (payment, Cont_val[t+1, hm_next, lm_next, lk_next])

    payoff_reorg, answer = findmax(reorg_value)
    
    return payoff_reorg, answer
end

function update_beliefs(propositor, hk_next, hm_next, lk_next, lm_next, t, tsym)
    
    if(t<=tsym)
        
        #t <= tsym, there is symmetric information
        
         if(propositor=="s")
            hst = hk_next
            lst = hk_next

            hjt = hm_next
            ljt = hm_next

        else
            hst = hm_next
            lst = hm_next

            hjt = hk_next
            ljt = hk_next
        end
        
    else
        
        #t > tsym, there is asymmetric information


        if(propositor=="s")
            hst = hk_next
            lst = lk_next

            hjt = hm_next
            ljt = lm_next

        else
            hst = hm_next
            lst = lm_next

            hjt = hk_next
            ljt = lk_next
        end
    end

    
    return hst, lst, hjt, ljt
end

        

update_beliefs (generic function with 1 method)

In [9]:
#código para tirar um draw da beta

function draw_beta(hkt, β=game_parameters[2], grid=100)

    u = rand()

    if(hkt == 100)
        
        return 100

    else
        
        x = 1.0 - exp(1.0/β * (log(1.0 - u) + β * log(1.0 - hkt/grid)))
        x = round(x * 100, digits=0)
#         return Int64(x * 100) #to convert in an integer
        return Int64(x)
        
    end
end

        

# @code_warntype draw_beta(10)



draw_beta (generic function with 3 methods)

In [10]:
function choose_parameters(propositor, hst, lst, hjt, ljt)
    
    if(propositor=="s")
        
        Pkt_array = Pst_array
        Cont_val = j_W
        prop_index = 1
        respondent_index = 2 #índice de j, para organizar o payoff
        m_L = j_L

        hkt = hst
        lkt = lst
        
        hmt = hjt
        lmt = ljt


        lk_next = hkt

        hk_next = draw_beta(hkt)
        hm_next = draw_beta(hmt)
        
    elseif(propositor=="j")
        Pkt_array = Pjt_array
        Cont_val = s_W
        prop_index = 2
        respondent_index = 1
        m_L = s_L

        hkt = hjt
        lkt = ljt
        
        hmt = hst
        lmt = lst


        lk_next = hkt


        hk_next = draw_beta(hkt)
        hm_next = draw_beta(hmt)

    else
        
        println("error: propositor not valid")
        
    end
    
    return Pkt_array, Cont_val, prop_index, respondent_index, m_L, hkt, lkt, hmt, lmt, lk_next, hk_next, hm_next
end




#test
Hs0 = 30
Hj0 = 28


hst = Hs0
hjt = Hj0

#assumindo que lower bounds nos períodos iniciais são as próprias habilidades iniciais
lst = hst
ljt = hjt




choose_parameters("s", hst, lst, hjt, ljt);
    
    

In [11]:
function simulate_game(Hs0, Hj0, μ, λj, counterfactual_parameters, s_W=s_W, j_W=j_W, Pst_array=Pst_array, Pjt_array=Pjt_array, t=1, grid=100)
    
    hst = Hs0
    hjt = Hj0

    #assumindo que lower bounds nos períodos iniciais são as próprias habilidades iniciais
    lst = hst
    ljt = hjt
    
    result = zeros(5);
    
    #number of observed proposals
    observed_proposals = 0.0
    
    
    #recovering "T+1" from s_W 
    T = size(s_W,1)
    
    
    #counterfactual parameters
    tsym = counterfactual_parameters[1]
    additional_cost = counterfactual_parameters[2]
    ac_s = counterfactual_parameters[3]
    ac_j = counterfactual_parameters[4];
    
    
    
    while(result[1]==0.0 && t < T)
        
        
        u = rand()

        if(u < λj)
            propositor = "j"

        else
            propositor = "s"

        end

        
        #setting the default variables according to the propositor
        Pkt_array, Cont_val, prop_index, respondent_index, m_L, hkt, lkt, hmt, lmt, lk_next, hk_next, hm_next = choose_parameters(propositor, hst, lst, hjt, ljt)
        
        
        #proposal ####
        policy, payoff_prop, payment, lm_next = proposal(Pkt_array, t, hkt, lmt)

        #lm_next is the update of the adversary's lower bound
        if(lm_next>=grid+1 || policy!= 3.0) #para evitar update de lowerbound quando proponente não propõe reorg
            lm_next = lmt
        else
            lm_next = Int64(lm_next)
        end
        
        
        
        if(policy==3.0)
            
            observed_proposals += 1.0
    
            payoff_respondent, answer = answer_reorg(payment, Cont_val, t, hm_next, lm_next, lk_next)


            if(answer==1.0)

                result[prop_index] = payoff_prop
                result[respondent_index] = payoff_respondent
                result[3] = 3.0
                result[4] = t
                result[5] = observed_proposals

            else
                
                t+=1

                hst, lst, hjt, ljt = update_beliefs(propositor, hk_next, hm_next, lk_next, lm_next, t, tsym)
            end

        elseif(policy==2.0)
            
            t+=1
            
            hst, lst, hjt, ljt = update_beliefs(propositor, hk_next, hm_next, lk_next, lm_next, t, tsym)
            
            

        else      
            #(policy==1.0)
            
            observed_proposals += 1.0

            payoff_respondent, answer = answer_liq(m_L, t, hm_next, payoff_prop, additional_cost, ac_s, ac_j)

            if(answer==1.0)

                result[prop_index] = payoff_prop
                result[respondent_index] = payoff_respondent
                result[3] = 1.0
                result[4] = t
                result[5] = observed_proposals

            else

                result[prop_index] = payoff_prop
                result[respondent_index] = payoff_respondent
                result[3] = 3.0
                result[4] = t
                result[5] = observed_proposals


            end
        end


        if(t==T)
            
            result[1] = s_W[T, 1, 1, 1]#todos os valores finais de S são iguais, então acessarei o índice 1
            result[2] = j_W[T, 1, 1, 1]
            result[3] = 1.0
            result[4] = t
            result[5] = max(observed_proposals, 1.0) #to avoid observed_proposals==0.0
            
        end
        




    end
    
    
    return result
end

        
        
#precisa colocar uma condição IF aqui para caso o jogo vá até o último período?
    

simulate_game (generic function with 7 methods)

In [12]:
# simulate_game(θs0, θj0, μ, λj, s_W, j_W, Pst_array, Pjt_array)

In [13]:
function loop_simulations(S, N, θs0, θj0, μ, λj, counterfactual_parameters, s_W=s_W, j_W=j_W, Pst_array=Pst_array, Pjt_array=Pjt_array)
    
    #S is the number of simulations
    #N is the number of observations
    
    #no futuro os argumentos podem ser arrays de arrays, assim ele faz o loop para cada cluster
    
    Results = zeros(S, N, 7)

    #últimas entradas de Results são os valores das dívidas
    Results[:,:, end-1] .= Dj
    Results[:,:, end] .= Ds


    for s in 1:S
        for n in 1:N
            Results[s,n,1:5] .= simulate_game(θs0, θj0, μ, λj, counterfactual_parameters)
        end
    end

    return Results
    
end

    
# loop_simulations(40, 75, θs0, θj0, μ, λj);

In [14]:
function simulate_moments(S, N, θs0, θj0, μ, λj, counterfactual_parameters, s_W=s_W, j_W=j_W, Pst_array=Pst_array, Pjt_array=Pjt_array)
    
    
    Results = loop_simulations(S, N, θs0, θj0, μ, λj, counterfactual_parameters)
    
    
    Moments = zeros(S, 8)
    
    
    for s in 1:S

            DF = DataFrame()
            DF.payoff_s = Results[s,:,1];
            DF.payoff_j = Results[s,:,2];
            DF.out = Results[s,:,3];
            DF.t = Results[s,:,4];
            DF.observed_proposals = Results[s,:,5];
            DF.Dj = Results[s,:,6];
            DF.Ds = Results[s,:,7];


            DF.outcome = ifelse.(DF.out .==3.0, "R", "L");


            #desfazendo o deslocamento no índice de t
            DF.t = DF.t .- 1.0;

            # DF.incourt = ifelse.(DF.t .> 0.0, "incourt", "precourt");

            INCOURT = filter(DF -> DF.t .> 0.0, DF);
            PRECOURT = filter(DF -> DF.t .<= 0.0, DF);

            PRECOURT_REORG = filter(PRECOURT -> PRECOURT.outcome .== "R", PRECOURT)
            INCOURT_REORG = filter(INCOURT -> INCOURT.outcome .== "R", INCOURT)

            #cálculo dos momentos
            #1. avg log number of months between observed proposals incourt

            mm1 = INCOURT
            mm1 = log.(mm1.t .* μ ./ mm1.observed_proposals)
            mm1 = mean(mm1)

            #2. fraction reorganized given that the case went into court

            mm2 = INCOURT
            mm2 = size(filter(mm2 -> mm2.outcome .== "R", mm2),1)/ size(mm2,1)

            #3. ln duration of court cases in months

            mm3 = INCOURT
            mm3 = filter(mm3 -> mm3.t .> 0.0, mm3) #removendo os casos 0 para não poluir a média
            mm3.t = mm3.t .* μ
            mm3 = mean(log.(mm3.t)) #log here uses exp as base, so it's the same as ln

            #4. fraction of cases incourt
            mm4 = size(INCOURT,1) / size(DF, 1)

            #5. avg recovery rate for senior given precourt REORGANIZATION

            #aqui nós temos Ds, então é mais fácil. Preciso automatizar isso no código quando for tudo escalado

            mm5 = PRECOURT_REORG
            mm5.R_s = mm5.payoff_s ./ mm5.Ds
            mm5 = mean(mm5.R_s)

            #if there are no precourt cases, it will return zero
            if(isnan(mm5))
                mm5 = zero(0.0)
            end


            #6. avg recovery rate for junior given precourt REORGANIZATION

            #aqui nós temos Ds, então é mais fácil. Preciso automatizar isso no código quando for tudo escalado

            mm6 = PRECOURT_REORG
            mm6.R_j = mm6.payoff_j ./ mm6.Dj
            mm6 = mean(mm6.R_j)

            #if there are no precourt cases, it will return zero
            if(isnan(mm6))
                mm6 = zero(0.0)
            end


            #7. junior avg fraction gain given incourt REORGANIZATION

            mm7 = INCOURT_REORG
            mm7 = mean(mm7.payoff_j ./ (mm7.payoff_j .+ mm7.payoff_s )) 

            #8. total recovery rate given incourt REORGANIZATION

            mm8 = INCOURT_REORG
            mm8 = mean( mm8.payoff_s .+ mm8.payoff_j)



            Moments[s,:] .= [mm1, mm2, mm3, mm4, mm5, mm6, mm7, mm8]

            #if there are no INCOURT or no PRECOURT cases, it will return NaN
            #thus, we replace it by zero
            Moments[s,:] .= replace!(Moments[s,:], NaN=> zero(0.0))

        end
    return vec(mean(Moments, dims=1))
end

simulate_moments (generic function with 5 methods)

In [15]:
using Random

In [16]:
Random.seed!(123);

In [17]:
#test
S = 40
N = 66


simulated_moments = simulate_moments(S, N, θs0, θj0, μ, λj, counterfactual_parameters)

8-element Array{Float64,1}:
 0.7913410679678007
 1.0
 2.0439931603666666
 0.9920454545454545
 0.42052405405405413
 0.3670327319143748
 0.7396036809070171
 0.5009733693532986

Comparing with the actual data moments

In [18]:
#data_moments
data_moments = [0.728, 0.843, 2.76, 0.969, 0.6235, 0.5569, 0.773, 0.497];

In [19]:
function error_vector(data_moments, simulated_moments)
    #two arrays with the data moments and the simulated moments
    
# #     return (simulated_moments .- data_moments) ./ data_moments
#     
    return (simulated_moments .- data_moments)
    
end

error_vector (generic function with 1 method)

In [20]:
error_vector(data_moments, simulated_moments)

8-element Array{Float64,1}:
  0.0633410679678007
  0.15700000000000003
 -0.7160068396333332
  0.02304545454545448
 -0.20297594594594592
 -0.18986726808562515
 -0.03339631909298291
  0.003973369353298617

Derivative of moments w.r.t. parameters

In [21]:
game_parameters
simulation_parameters

3-element Array{Float64,1}:
 45.0
 99.0
  3.11

Derivative w.r.t. to $\rho$

In [22]:
#changing from 0.52 to 0.53
game_parameters[1] = 0.53

0.53

In [23]:
game_parameters

4-element Array{Float64,1}:
  0.53
 22.59
  0.2
  0.01

In [24]:
s_W, j_W, Pst_array, Pjt_array, Ds, Dj = solve_tree(data, game_parameters, counterfactual_parameters);

  4.583231 seconds (43.22 M allocations: 858.002 MiB, 2.27% gc time)
  7.898391 seconds (43.22 M allocations: 858.002 MiB, 1.44% gc time)
  8.911555 seconds (43.22 M allocations: 858.002 MiB, 1.35% gc time)
  9.133704 seconds (40.16 M allocations: 811.310 MiB, 1.20% gc time)
 30.837155 seconds (169.82 M allocations: 3.306 GiB, 1.45% gc time)


In [25]:
θs0, θj0, μ = simulation_parameters;
θs0 = Int64(θs0);
θj0 = Int64(θj0);

λj = game_parameters[4];

In [26]:
new_simulated_moments = simulate_moments(S, N, θs0, θj0, μ, λj, counterfactual_parameters)

8-element Array{Float64,1}:
 0.8468760916818384
 1.0
 1.9927716835969727
 0.9928030303030303
 0.41644513513513515
 0.4049620840856666
 0.7602188530966536
 0.5431488406937196

In [27]:
new_simulated_moments - simulated_moments

8-element Array{Float64,1}:
  0.055535023714037735
  0.0
 -0.05122147676969391
  0.0007575757575758457
 -0.004078918918918983
  0.037929352171291786
  0.020615172189636488
  0.04217547134042099

In [28]:
game_parameters * 0.01

4-element Array{Float64,1}:
 0.0053
 0.2259
 0.002
 0.0001

In [29]:
simulation_parameters * 0.01

3-element Array{Float64,1}:
 0.45
 0.99
 0.0311

In [30]:
#calculando a derivada em relação a ρ

function derivative_moments(S, N, game_parameters, simulation_parameters, counterfactual_parameters, simulated_moments)
    
    
    P = size(game_parameters,1)+size(simulation_parameters,1)
    M = size(simulated_moments,1)
    D = zeros(M, P)
    
    estimated_game_parameters = game_parameters
    estimated_simulation_parameters = simulation_parameters
    
    #delta for each parameter
    #approximately 1% or the lowest decimal point
    #[game_parameters, simulation_parameters]
    delta = [0.01, 0.22, 0.002, 0.01, 1.0, 1.0, 0.03]
    
    for i in 1:P
        if(i<=size(game_parameters,1))
            game_parameters = copy(estimated_game_parameters)
            
            game_parameters[i] = game_parameters[i] + delta[i]
            
        else
            simulation_parameters = copy(estimated_simulation_parameters)
            simulation_parameters[i-size(game_parameters,1)] = simulation_parameters[i-size(game_parameters,1)] + delta[i]
            
            
        end
        
    
        θs0, θj0, μ = simulation_parameters;
        θs0 = Int64(round(θs0, digits=0));
        θj0 = Int64(round(θj0, digits=0));

        λj = game_parameters[4];

        s_W, j_W, Pst_array, Pjt_array, Ds, Dj = solve_tree(data, game_parameters, counterfactual_parameters);
        new_simulated_moments = simulate_moments(S, N, θs0, θj0, μ, λj, counterfactual_parameters)
        
        D[:, i] = new_simulated_moments - simulated_moments
        
    end
    
    
    
    return D
    
end


derivative_moments (generic function with 1 method)

In [31]:
D = derivative_moments(S, N, game_parameters, simulation_parameters, counterfactual_parameters, simulated_moments)

  5.064712 seconds (43.22 M allocations: 858.002 MiB, 6.22% gc time)
  8.142379 seconds (43.22 M allocations: 858.002 MiB, 1.28% gc time)
  8.929732 seconds (43.22 M allocations: 858.002 MiB, 1.14% gc time)
  9.407681 seconds (40.16 M allocations: 811.310 MiB, 1.06% gc time)
 31.772078 seconds (169.82 M allocations: 3.306 GiB, 1.95% gc time)
  4.722656 seconds (43.22 M allocations: 858.002 MiB, 3.22% gc time)
  8.001295 seconds (43.22 M allocations: 858.002 MiB, 1.36% gc time)
  8.994210 seconds (43.22 M allocations: 858.002 MiB, 1.27% gc time)
  9.309080 seconds (40.16 M allocations: 811.310 MiB, 1.28% gc time)
 31.179673 seconds (169.82 M allocations: 3.306 GiB, 1.58% gc time)
  4.598813 seconds (43.22 M allocations: 858.002 MiB, 2.20% gc time)
  7.875185 seconds (43.22 M allocations: 858.002 MiB, 1.78% gc time)
  8.976042 seconds (43.22 M allocations: 858.002 MiB, 1.44% gc time)
  9.233771 seconds (40.16 M allocations: 811.310 MiB, 1.09% gc time)
 30.930084 seconds (169.82 M allocat

8×7 Array{Float64,2}:
  0.0515188    0.0493572   0.0557503   …  -0.0842709   0.0660739
  0.0          0.0         0.0             0.0         0.0
 -0.0594556   -0.0542616  -0.0501574      -0.233582   -0.048092
 -0.00113636   0.0        -0.00340909     -0.0106061  -0.00795455
  0.144651     0.0256672   0.23389         0.391938    0.293382
  0.182559     0.0668552   0.269336    …   0.458453    0.327188
  0.0238279    0.0231585   0.0198318       0.0572709   0.0186821
  0.0482291    0.0450781   0.0408163       0.205444    0.0425594