Tentando calcular as funções influência dos momentos que vou usar na estimação

1. Ler os dados do projeto dentro de Julia
2. Calcular os momentos usando os dados
3. Calcular IF
    * se a observação não pertence ao conjunto (i.e., o momento é sobre casos pré-corte e a observação fica dentro da corte), IF = 0
    * do contrário, IF = x - Momento(X), onde x é a observação e X é a amostra correspondente àquele momento

Estamos trocando alguns momentos

- 5 e 6 serão taxas de recuperação para S e J em casos "rápidos" reorganizados dentro da corte
    - entrarão no lugar da taxa de recuperação pre-court, pois temos só 2 observações para estes
    
- 9 e 10 serão as variâncias das taxas de recuperação de S e J para reorganizações dentro da corte
    - mais momentos para identificar habilidades iniciais de S e de J
    
- 11 será a variância da duração total de casos ~reorganizados~ dentro da corte
    - ajudará a identificar \rho, torcemos
    - teste no aguia foi com casos reorganizados, mas o MM3 é a média da duração de todos os casos dentro da corte. Portanto, vou calcular a variância de todos os casos dentro da corte no MM11
    
- 12 será o coeficiente da regressão da taxa de recuperação total na duração total para casos reorganizados dentro da corte
    - é o momento 9 de Dou et al, que serve para identificar \rho

In [1]:
#lendo dados do projeto: trilemma_data.xlsx
# using Pkg
# Pkg.add("XLSX")

using XLSX

In [2]:
using DataFrames

In [3]:
using Statistics

In [4]:
ENV["COLUMNS"] = 240 #para aumentar o número de colunas mostradas

240

In [5]:
df = DataFrame(XLSX.readtable("trilemma_data.xlsx", "Sheet1")...)

66×32 DataFrame. Omitted printing of 17 columns
│ Row │ processo                  │ fil_date   │ data_start │ plan_date  │ final_date │ months_fil_start │ months_start_plan │ months_plan_final │ months_fil_final │ in_court │ D_junior  │ D_labor   │ D_senior  │ R_junior │ R_labor  │
│     │ Any                       │ Any        │ Any        │ Any        │ Any        │ Any              │ Any               │ Any               │ Any              │ Any      │ Any       │ Any       │ Any       │ Any      │ Any      │
├─────┼───────────────────────────┼────────────┼────────────┼────────────┼────────────┼──────────────────┼───────────────────┼───────────────────┼──────────────────┼──────────┼───────────┼───────────┼───────────┼──────────┼──────────┤
│ 1   │ 0000547-55.2014.8.26.0291 │ 2014-01-22 │ 2014-01-29 │ 2015-09-16 │ 2018-07-12 │ 0.233333         │ 19.8333           │ 34.3333           │ 54.4             │ 1.0      │ 3.49201e6 │ 1.38557e6 │ 3.656e6   │ 0.442533 │ 0.941905 │
│ 2   │ 0000731-65.2011.8.26.0695 │ 2011-03-22 │ 2011-04-08 │ 2011-10-20 │ 2017-04-20 │ 0.566667         │ 6.5               │ 66.9667           │ 74.0333          │ 1.0      │ 1.58332e6 │ 9.64064e5 │ 1.61192e5 │ 0.81201  │ 0.941905 │
│ 3   │ 0003124-79.2014.8.26.0299 │ 2014-05-28 │ 2014-09-25 │ 2016-07-18 │ 2018-07-02 │ 4.0              │ 22.0667           │ 23.8              │ 49.8667          │ 1.0      │ 9.85081e6 │ 1.63535e5 │ 3.30049e6 │ 0.36744  │ 0.968244 │
│ 4   │ 0006202-38.2010.8.26.0100 │ 2010-02-12 │ 2010-03-29 │ 2011-01-03 │ 2017-08-25 │ 1.5              │ 9.33333           │ 80.8667           │ 91.7             │ 1.0      │ 3.58351e7 │ 1.72202e6 │ 4.18984e5 │ 0.535184 │ 0.941905 │
│ 5   │ 0011100-26.2012.8.26.0100 │ 2012-03-06 │ 2012-04-04 │ 2014-05-15 │ 2015-11-24 │ 0.966667         │ 25.7              │ 18.6              │ 45.2667          │ 1.0      │ 1.43452e7 │ 0.0       │ 1.41472e7 │ 0.465931 │ 0.0      │
│ 6   │ 0014297-52.2013.8.26.0100 │ 2013-02-07 │ 2013-02-22 │ 2014-07-21 │ 2018-05-15 │ 0.5              │ 17.1333           │ 46.4667           │ 64.1             │ 1.0      │ 3.1438e7  │ 1.41865e6 │ 1.48989e7 │ 0.396523 │ 0.941905 │
│ 7   │ 0016095-59.2013.8.26.0161 │ 2013-06-17 │ 2014-03-18 │ 2016-06-06 │ 2018-11-01 │ 9.13333          │ 27.0333           │ 29.2667           │ 65.4333          │ 1.0      │ 1.00002e7 │ 75754.0   │ 1.02842e5 │ 0.814917 │ 0.941905 │
│ 8   │ 0023189-81.2012.8.26.0100 │ 2012-05-07 │ 2012-06-22 │ 2013-06-07 │ 2019-01-15 │ 1.53333          │ 11.6667           │ 68.2667           │ 81.4667          │ 1.0      │ 4.86213e6 │ 0.0       │ 3.844e6   │ 0.206332 │ 0.0      │
│ 9   │ 0025113-93.2013.8.26.0100 │ 2013-04-03 │ 2013-08-16 │ 2014-09-17 │ 2018-09-24 │ 4.5              │ 13.2333           │ 48.9333           │ 66.6667          │ 1.0      │ 1.07158e6 │ 0.0       │ 150000.0  │ 0.448017 │ 0.0      │
│ 10  │ 0025535-05.2012.8.26.0100 │ 2012-05-18 │ 2012-09-03 │ 2013-06-07 │ 2015-10-08 │ 3.6              │ 9.23333           │ 28.4333           │ 41.2667          │ 1.0      │ 8.35837e6 │ 3.05502e5 │ 1.26003e6 │ 0.726299 │ 0.941905 │
⋮
│ 56  │ 1085873-20.2015.8.26.0100 │ 2015-08-24 │ 2016-03-16 │ 2017-05-09 │ 2018-08-10 │ 6.83333          │ 13.9667           │ 15.2667           │ 36.0667          │ 1.0      │ 3.39584e6 │ 4085.73   │ 7.72192e5 │ 0.512246 │ 0.941905 │
│ 57  │ 1085973-43.2013.8.26.0100 │ 2013-11-01 │ 2013-11-22 │ 2014-12-10 │ 2017-03-14 │ 0.7              │ 12.7667           │ 27.5              │ 40.9667          │ 1.0      │ 3.1628e8  │ 1.76287e7 │ 9.46264e7 │ 0.596823 │ 0.941905 │
│ 58  │ 1093571-43.2016.8.26.0100 │ 2016-08-23 │ 2016-08-24 │ 2018-06-06 │ 2018-06-06 │ 0.0333333        │ 21.7              │ 0.0               │ 21.7333          │ 1.0      │ 5.39331e7 │ 6.40385e6 │ 7.27368e6 │ 0.298644 │ 0.941905 │
│ 59  │ 1094025-28.2013.8.26.0100 │ 2013-11-26 │ 2014-01-30 │ 2014-11-07 │ 2017-02-09 │ 2.16667          │ 9.36667           │ 27.5              │ 39.0333          │ 1.0      │ 1.35187e7 │ 2

In [6]:
names(df)

32-element Array{Symbol,1}:
 :processo
 :fil_date
 :data_start
 :plan_date
 :final_date
 :months_fil_start
 :months_start_plan
 :months_plan_final
 :months_fil_final
 :in_court
 :D_junior
 :D_labor
 :D_senior
 ⋮
 :Vh
 :L
 :D
 :Dj_D
 :L_D
 :Vh_D
 :Reorg_incourt
 :Reorg_precourt
 :Liq_incourt
 :Liq_precourt
 :tempo_medio_agc
 :ln_n_months

In [7]:
INCOURT = filter(df -> df.in_court .== 1.0, df);
PRECOURT = filter(df -> df.in_court .== 0.0, df);

In [8]:
filter(INCOURT -> INCOURT.months_start_plan .== 0, INCOURT)

0×32 DataFrame

MM1: average log number of months between observed proposals, for incourt cases

In [9]:
mm1 = mean(skipmissing(df.ln_n_months))

2.1118291318473066

In [10]:
if1 = zeros(nrow(df));

for i in 1:length(if1)
    if(ismissing(df.ln_n_months[i]))
        if1[i] = zero(0.0)
    else
        if1[i] = df.ln_n_months[i] - mm1
    end
end

#testando se a média é maior que zero
#qual seria o zero em Julia?
mean(if1)> 0.000000000000001

false

In [11]:
if1

66-element Array{Float64,1}:
  0.18238771147622224
  0.0
  0.0
  0.12176308965978766
  0.4415146794939222
  0.036049571385757595
  1.185241540605951
 -1.9576784520200483
  0.47090976717772826
  0.0
  1.0280034856804412
 -0.6787307045296134
  0.0
  ⋮
  0.6935494132154658
  0.0
 -0.6636038129969257
  0.0
  0.1253281558242838
  0.0
  0.8430811471864295
  0.0
 -0.9162245771918873
  0.0
  0.0
  0.0

MM2: fraction reorganized given that the case went into court

In [12]:
mm2 = INCOURT
mm2 = size(filter(mm2 -> mm2.outcome_bargain .== "reorganized", mm2),1)/ size(mm2,1)

0.84375

In [13]:
if2 = zeros(nrow(df));

for i in 1:length(if2)
    if(df.in_court[i]==0.0)
        if2[i] = zero(0.0)
    else
        if2[i] = df.Reorg_incourt[i] - mm2
    end
end

mean(if2)

0.0

MM3: avg ln duration of court cases in months

In [14]:
mm3 = mean(log.(INCOURT.months_start_plan))

2.760695631787451

In [15]:
if3 = zeros(nrow(df));

for i in 1:length(if3)
    if(df.in_court[i]==0.0)
        if3[i] = zero(0.0)
    else
        if3[i] = log(df.months_start_plan[i]) - mm3
    end
end

mean(if3)

2.4895910249170175e-16

MM4: Fraction of cases incourt

In [16]:
mm4 = mean(df.in_court)

0.9696969696969697

In [17]:
#função influência do mm4:
if4 = zeros(nrow(df));

# for i in 1:length(if4)
#     println(i)
# end

for i in 1:length(if4)
    if4[i] = df.in_court[i] - mm4
end

In [18]:
mean(if4)

-2.6914497566670462e-17

MM5: avg recovery rate for S given REORGANIZATION in the 25% fastest cases

Includes PRECOURT and INCOURT cases

In [33]:
q = 0.25 #quartil desejado


mm5 = filter(df -> df.outcome_bargain .== "reorganized", df) #casos reorganizados, dentro ou fora da corte

56×32 DataFrame. Omitted printing of 17 columns
│ Row │ processo                  │ fil_date   │ data_start │ plan_date  │ final_date │ months_fil_start │ months_start_plan │ months_plan_final │ months_fil_final │ in_court │ D_junior  │ D_labor   │ D_senior  │ R_junior │ R_labor  │
│     │ Any                       │ Any        │ Any        │ Any        │ Any        │ Any              │ Any               │ Any               │ Any              │ Any      │ Any       │ Any       │ Any       │ Any      │ Any      │
├─────┼───────────────────────────┼────────────┼────────────┼────────────┼────────────┼──────────────────┼───────────────────┼───────────────────┼──────────────────┼──────────┼───────────┼───────────┼───────────┼──────────┼──────────┤
│ 1   │ 0000547-55.2014.8.26.0291 │ 2014-01-22 │ 2014-01-29 │ 2015-09-16 │ 2018-07-12 │ 0.233333         │ 19.8333           │ 34.3333           │ 54.4             │ 1.0      │ 3.49201e6 │ 1.38557e6 │ 3.656e6   │ 0.442533 │ 0.941905 │
│ 2   │ 0000731-65.2011.8.26.0695 │ 2011-03-22 │ 2011-04-08 │ 2011-10-20 │ 2017-04-20 │ 0.566667         │ 6.5               │ 66.9667           │ 74.0333          │ 1.0      │ 1.58332e6 │ 9.64064e5 │ 1.61192e5 │ 0.81201  │ 0.941905 │
│ 3   │ 0003124-79.2014.8.26.0299 │ 2014-05-28 │ 2014-09-25 │ 2016-07-18 │ 2018-07-02 │ 4.0              │ 22.0667           │ 23.8              │ 49.8667          │ 1.0      │ 9.85081e6 │ 1.63535e5 │ 3.30049e6 │ 0.36744  │ 0.968244 │
│ 4   │ 0006202-38.2010.8.26.0100 │ 2010-02-12 │ 2010-03-29 │ 2011-01-03 │ 2017-08-25 │ 1.5              │ 9.33333           │ 80.8667           │ 91.7             │ 1.0      │ 3.58351e7 │ 1.72202e6 │ 4.18984e5 │ 0.535184 │ 0.941905 │
│ 5   │ 0011100-26.2012.8.26.0100 │ 2012-03-06 │ 2012-04-04 │ 2014-05-15 │ 2015-11-24 │ 0.966667         │ 25.7              │ 18.6              │ 45.2667          │ 1.0      │ 1.43452e7 │ 0.0       │ 1.41472e7 │ 0.465931 │ 0.0      │
│ 6   │ 0014297-52.2013.8.26.0100 │ 2013-02-07 │ 2013-02-22 │ 2014-07-21 │ 2018-05-15 │ 0.5              │ 17.1333           │ 46.4667           │ 64.1             │ 1.0      │ 3.1438e7  │ 1.41865e6 │ 1.48989e7 │ 0.396523 │ 0.941905 │
│ 7   │ 0016095-59.2013.8.26.0161 │ 2013-06-17 │ 2014-03-18 │ 2016-06-06 │ 2018-11-01 │ 9.13333          │ 27.0333           │ 29.2667           │ 65.4333          │ 1.0      │ 1.00002e7 │ 75754.0   │ 1.02842e5 │ 0.814917 │ 0.941905 │
│ 8   │ 0023189-81.2012.8.26.0100 │ 2012-05-07 │ 2012-06-22 │ 2013-06-07 │ 2019-01-15 │ 1.53333          │ 11.6667           │ 68.2667           │ 81.4667          │ 1.0      │ 4.86213e6 │ 0.0       │ 3.844e6   │ 0.206332 │ 0.0      │
│ 9   │ 0025113-93.2013.8.26.0100 │ 2013-04-03 │ 2013-08-16 │ 2014-09-17 │ 2018-09-24 │ 4.5              │ 13.2333           │ 48.9333           │ 66.6667          │ 1.0      │ 1.07158e6 │ 0.0       │ 150000.0  │ 0.448017 │ 0.0      │
│ 10  │ 0025535-05.2012.8.26.0100 │ 2012-05-18 │ 2012-09-03 │ 2013-06-07 │ 2015-10-08 │ 3.6              │ 9.23333           │ 28.4333           │ 41.2667          │ 1.0      │ 8.35837e6 │ 3.05502e5 │ 1.26003e6 │ 0.726299 │ 0.941905 │
⋮
│ 46  │ 1070215-24.2013.8.26.0100 │ 2013-09-20 │ 2013-10-10 │ 2014-12-05 │ 2019-04-17 │ 0.666667         │ 14.0333           │ 53.1333           │ 67.8333          │ 1.0      │ 2.98002e7 │ 1.16364e6 │ 3.92611e6 │ 0.746609 │ 0.946686 │
│ 47  │ 1079269-43.2015.8.26.0100 │ 2015-08-06 │ 2015-11-06 │ 2017-03-16 │ 2020-01-09 │ 3.06667          │ 16.5333           │ 34.3              │ 53.9             │ 1.0      │ 2.1325e6  │ 2.7641e5  │ 27120.0   │ 0.299413 │ 0.963383 │
│ 48  │ 1085873-20.2015.8.26.0100 │ 2015-08-24 │ 2016-03-16 │ 2017-05-09 │ 2018-08-10 │ 6.83333          │ 13.9667           │ 15.2667           │ 36.0667          │ 1.0      │ 3.39584e6 │ 4085.73   │ 7.72192e5 │ 0.512246 │ 0.941905 │
│ 49  │ 1085973-43.2013.8.26.0100 │ 2013-11-01 │ 2013-11-22 │ 2014-12-10 │ 2017-03-14 │ 0.7              │ 12.7667           │ 27.5              │ 40.9667          │ 1.0      │ 3.1628e8  │ 1

In [34]:
quartil = quantile(log.(mm5.months_start_plan), q)

2.348195604246101

In [35]:
mm5 = filter(mm5 -> log.(mm5.months_start_plan) .<= quartil, mm5)

15×32 DataFrame. Omitted printing of 17 columns
│ Row │ processo                  │ fil_date   │ data_start │ plan_date  │ final_date │ months_fil_start │ months_start_plan │ months_plan_final │ months_fil_final │ in_court │ D_junior  │ D_labor   │ D_senior  │ R_junior │ R_labor  │
│     │ Any                       │ Any        │ Any        │ Any        │ Any        │ Any              │ Any               │ Any               │ Any              │ Any      │ Any       │ Any       │ Any       │ Any      │ Any      │
├─────┼───────────────────────────┼────────────┼────────────┼────────────┼────────────┼──────────────────┼───────────────────┼───────────────────┼──────────────────┼──────────┼───────────┼───────────┼───────────┼──────────┼──────────┤
│ 1   │ 0000731-65.2011.8.26.0695 │ 2011-03-22 │ 2011-04-08 │ 2011-10-20 │ 2017-04-20 │ 0.566667         │ 6.5               │ 66.9667           │ 74.0333          │ 1.0      │ 1.58332e6 │ 9.64064e5 │ 1.61192e5 │ 0.81201  │ 0.941905 │
│ 2   │ 0006202-38.2010.8.26.0100 │ 2010-02-12 │ 2010-03-29 │ 2011-01-03 │ 2017-08-25 │ 1.5              │ 9.33333           │ 80.8667           │ 91.7             │ 1.0      │ 3.58351e7 │ 1.72202e6 │ 4.18984e5 │ 0.535184 │ 0.941905 │
│ 3   │ 0025535-05.2012.8.26.0100 │ 2012-05-18 │ 2012-09-03 │ 2013-06-07 │ 2015-10-08 │ 3.6              │ 9.23333           │ 28.4333           │ 41.2667          │ 1.0      │ 8.35837e6 │ 3.05502e5 │ 1.26003e6 │ 0.726299 │ 0.941905 │
│ 4   │ 0133085-64.2009.8.26.0100 │ 2009-04-01 │ 2009-05-19 │ 2010-03-19 │ 2018-12-04 │ 1.6              │ 10.1333           │ 106.067           │ 117.8            │ 1.0      │ 1.66432e7 │ 89600.0   │ 1.12e6    │ 0.377744 │ 0.995025 │
│ 5   │ 0199374-13.2008.8.26.0100 │ 2008-09-23 │ 2008-10-30 │ 2009-09-09 │ 2017-09-20 │ 1.23333          │ 10.4667           │ 97.7667           │ 109.467          │ 1.0      │ 6.89941e6 │ 11642.0   │ 1.16586e6 │ 0.687773 │ 0.941905 │
│ 6   │ 0228439-53.2008.8.26.0100 │ 2008-06-15 │ 2009-01-09 │ 2009-11-12 │ 2016-04-19 │ 6.93333          │ 10.2333           │ 78.3333           │ 95.5             │ 1.0      │ 4.24744e7 │ 9.57444e5 │ 684573.0  │ 0.598274 │ 0.941905 │
│ 7   │ 1001156-81.2014.8.26.0077 │ 2014-02-25 │ 2014-03-07 │ 2015-01-15 │ 2018-10-16 │ 0.333333         │ 10.4667           │ 45.6667           │ 56.4667          │ 1.0      │ 1.73876e6 │ 86650.6   │ 8.51832e5 │ 0.173783 │ 0.941746 │
│ 8   │ 1006499-72.2016.8.26.0664 │ 2016-08-09 │ 2016-09-12 │ 2017-06-07 │ 2019-08-14 │ 1.13333          │ 8.93333           │ 26.6              │ 36.6667          │ 1.0      │ 1.67434e6 │ 60166.6   │ 4.18353e6 │ 0.182776 │ 0.953758 │
│ 9   │ 1015481-89.2014.8.26.0100 │ 2014-02-18 │ 2014-03-20 │ 2014-11-06 │ 2017-05-16 │ 1.0              │ 7.7               │ 30.7333           │ 39.4333          │ 1.0      │ 6.36258e6 │ 3.82754e5 │ 1.26671e7 │ 0.278199 │ 0.941905 │
│ 10  │ 1065228-08.2014.8.26.0100 │ 2014-07-16 │ 2014-08-08 │ 2015-05-26 │ 2017-09-20 │ 0.766667         │ 9.7               │ 28.2667           │ 38.7333          │ 1.0      │ 6.06683e6 │ 1.26824e5 │ 6.78687e6 │ 0.995025 │ 1.0      │
│ 11  │ 1065329-11.2015.8.26.0100 │ 2015-07-01 │ 2015-08-04 │ 2016-05-13 │ 2019-03-20 │ 1.13333          │ 9.43333           │ 34.7              │ 45.2667          │ 1.0      │ 2.10363e6 │ 90000.0   │ 68675.0   │ 0.631971 │ 0.953758 │
│ 12  │ 1094025-28.2013.8.26.0100 │ 2013-11-26 │ 2014-01-30 │ 2014-11-07 │ 2017-02-09 │ 2.16667          │ 9.36667           │ 27.5              │ 39.0333          │ 1.0      │ 1.35187e7 │ 2.0442e6  │ 1.27225e6 │ 0.748413 │ 0.941905 │
│ 13  │ 1106266-34.2013.8.26.0100 │ 2014-01-07 │ 2014-01-30 │ 2014-10-29 │ 2018-12-05 │ 0.766667         │ 9.06667           │ 49.9333           │ 59.7667          │ 1.0      │ 1.072e7   │ 737470.0  │ 466674.0  │ 0.482878 │ 0.941905 │
│ 14  │ 1071904-64.2017.8.26.0100 │ 0          │ 0          │ 0          │ 0          │ 0.0              │ 0.0               │ 0.0               │ 0.0              │ 0.0      │ 1.66866e9 │ 0.0

In [36]:
mm5 = mean(mm5.R_senior)

0.5652848834410633

In [37]:
quartil

2.348195604246101

In [38]:
if5 = zeros(nrow(df));

for i in 1:length(if5)
    #casos liquidados ou que não estão entre os 25% reorganizados mais rapidamente não influenciam este momento
    if(df.outcome_bargain[i] == "liquidated")
        if5[i] = zero(0.0)
    elseif( (df.outcome_bargain[i] == "reorganized" && log(df.months_start_plan[i]) > quartil ) )
        if5[i] = zero(0.0)
    else
        if5[i] = df.R_senior[i] - mm5
    end
end

mean(if5)

5.046468293750712e-18

In [39]:
#se a IF estiver certa, somente 15 observações não terão valor zero
size(filter(if5 -> if5 .!= 0.0, if5), 1)

#bingo!

15

MM6: avg recovery arte for J given REORGANIZATION in the 25% fastest cases

Includes PRECOURT and INCOURT cases

In [40]:
q = 0.25 #quartil desejado

mm6 = filter(df -> df.outcome_bargain .== "reorganized", df) #casos reorganizados, dentro ou fora da corte

quartil = quantile(log.(mm6.months_start_plan), q)

mm6 = filter(mm6 -> log.(mm6.months_start_plan) .<= quartil, mm6)

mm6 = mean(mm6.R_junior)

0.5562758267330555

In [41]:
if6 = zeros(nrow(df));

for i in 1:length(if6)
    #casos liquidados ou que não estão entre os 25% reorganizados mais rapidamente não influenciam este momento
    if(df.outcome_bargain[i] == "liquidated")
        if6[i] = zero(0.0)
    elseif( (df.outcome_bargain[i] == "reorganized" && log(df.months_start_plan[i]) > quartil ) )
        if6[i] = zero(0.0)
    else
        if6[i] = df.R_junior[i] - mm6
    end
end



mean(if6)

3.027880976250427e-17

In [42]:
#se a IF estiver certa, somente 15 observações não terão valor zero
size(filter(if6 -> if6 .!= 0.0, if6), 1)
#bingo!

15

MM7: junior creditor’s average fraction gain, conditional on an in-court reorganization

In [43]:
INCOURT_REORG = filter(INCOURT -> INCOURT.outcome_bargain .== "reorganized", INCOURT);

In [44]:
INCOURT_REORG.payoff_j = INCOURT_REORG.R_junior .* INCOURT_REORG.D_junior;
INCOURT_REORG.payoff_s = INCOURT_REORG.R_senior .* INCOURT_REORG.D_senior;

In [45]:
mm7 = INCOURT_REORG
mm7 = mean(mm7.payoff_j ./ (mm7.payoff_j .+ mm7.payoff_s ))

0.7733661464016862

In [46]:
df.payoff_j = df.R_junior .* df.D_junior;
df.payoff_s = df.R_senior .* df.D_senior;

In [47]:
if7 = zeros(nrow(df));

for i in 1:length(if7)
    if(df.Reorg_incourt[i]== 0.0) #zero se a observação não for de reorganização dentro da corte
        if7[i] = zero(0.0)
    else
        if7[i] = (df.payoff_j[i] / (df.payoff_j[i] + df.payoff_s[i]) ) - mm7
    end
end

mean(if7)

-3.1960965860421176e-17

MM8: avg total recovery rate given incourt REORGANIZATION

In [48]:
mm8 = INCOURT_REORG
mm8 = mean((mm8.payoff_s .+ mm8.payoff_j) ./ (mm8.D_senior .+ mm8.D_junior))

0.4977287552407836

In [49]:
if8 = zeros(nrow(df));

for i in 1:length(if8)
    if(df.Reorg_incourt[i]==0.0) #zero se a observação não for de reorganização dentro da corte
        if8[i] = zero(0.0)
    else
        if8[i] = ((df.payoff_s[i] + df.payoff_j[i]) / (df.D_senior[i] + df.D_junior[i] ) )  - mm8
    end
end

mean(if8)

-9.25185853854297e-18

MM9: variance of recovery rate of S given INCOURT REORG

In [50]:
mm9 = INCOURT_REORG
mm9 = var(mm9.R_senior)

0.04652980615833147

In [51]:
if9 = zeros(nrow(df));

for i in 1:length(if9)
    if(df.Reorg_incourt[i]==0.0) #zero se a observação não for de reorganização dentro da corte
        if9[i] = zero(0.0)
    else
        if9[i] = (df.R_senior[i] - mean(INCOURT_REORG.R_senior))^2  - mm9
    end
end

mean(if9)

-0.0007049970630050308

MM10: variance of recovery rate of J given INCOURT REORG

In [79]:
mm10 = INCOURT_REORG
mm10 = var(mm10.R_junior)

0.03647614100988236

In [80]:
if10 = zeros(nrow(df));

for i in 1:length(if10)
    if(df.Reorg_incourt[i]==0.0) #zero se a observação não for de reorganização dentro da corte
        if10[i] = zero(0.0)
    else
        if10[i] = (df.R_junior[i] - mean(INCOURT_REORG.R_junior))^2  - mm10
    end
end

mean(if10)

-0.0005526688031800269

Testando como fica se usar a taxa de recuperação total

In [77]:
INCOURT_REORG.rr = ( (INCOURT_REORG.payoff_s .+ INCOURT_REORG.payoff_j) ./ (INCOURT_REORG.D_senior .+ INCOURT_REORG.D_junior) )

mm100 = INCOURT_REORG
mm100 = var(mm100.rr)

df.rr = ( (df.payoff_s .+ df.payoff_j) ./ (df.D_senior .+ df.D_junior) )

66-element Array{Float64,1}:
 0.4425333996263
 0.812009697811747
 0.367439910190618
 0.535183598438483
 0.465931221036928
 0.4416031370374372
 0.814917171851546
 0.206331898180979
 0.448016770448892
 0.726299399948863
 0.20834879710153104
 0.3846136940315716
 0.419574055786703
 ⋮
 0.30317247680794723
 0.512245559288437
 0.596822618043636
 0.29864371831563
 0.7291006110543988
 0.4828776301319899
 0.3691996989202075
 0.4018748061869991
 0.3503033948177223
 0.44147525898718404
 0.8054827368715078
 0.42502758660975737

In [78]:
if100 = zeros(nrow(df));

for i in 1:length(if100)
    if(df.Reorg_incourt[i]==0.0) #zero se a observação não for de reorganização dentro da corte
        if100[i] = zero(0.0)
    else
        if100[i] = (df.rr[i] - mean(INCOURT_REORG.rr))^2  - mm100
    end
end

mean(if100)

-0.0005669778797462191

MM11: variance ln duration of court cases in months

É a parte de variância, ao invés da média (MM3)

In [54]:
mm11 = var(log.(INCOURT.months_start_plan))

0.16966778593934911

In [56]:
if11 = zeros(nrow(df));

for i in 1:length(if11)
    if(df.in_court[i]==0.0) #zero se a observação não for dentro da corte
        if11[i] = zero(0.0)
    else
        if11[i] = (log(df.months_start_plan[i]) - mean(log.(INCOURT.months_start_plan)) )^2  - mm11
    end
end

mean(if11)

-0.0025707240293840364

MM12: slope of regression of total recovery rate on total duration for incourt reorganizations

Igual ao MM9 de Dou et al

In [57]:
y = INCOURT_REORG

y = log.(y.months_start_plan)

x = INCOURT_REORG
x = log.( (x.payoff_s .+ x.payoff_j) ./ (x.D_senior .+ x.D_junior))

X = [ones(size(x,1)) x]

using LinearAlgebra
mm12 = (X' * X) \ (X' * y)

mm12 = mm12[2]

-0.09822867075174749

In [58]:
if12 = zeros(nrow(df));

length(if12)

66

In [59]:
if12 = zeros(nrow(df));

#precisa recriar y e x aqui embaixo para englobar todas va
Y = log.(df.months_start_plan)
X = log.( (df.payoff_s .+ df.payoff_j) ./ (df.D_senior .+ df.D_junior))

66-element Array{Float64,1}:
 -0.815239338001109
 -0.2082429957738625
 -1.0011954833838048
 -0.6251454163057129
 -0.763717250090964
 -0.817343680245939
 -0.20466880053592001
 -1.5782692504939808
 -0.8029246132300827
 -0.3197929525456788
 -1.568541694581116
 -0.9555158405550106
 -0.8685152351945186
  ⋮
 -1.193453405033666
 -0.66895116093255
 -0.5161353319440475
 -1.208503993624127
 -0.31594354407601666
 -0.727992011193047
 -0.9964175918461682
 -0.9116146662622224
 -1.0489556576531676
 -0.8176332990424642
 -0.21631350816334852
 -0.8556012024942443

In [60]:
for i in 1:length(if12)
    if(df.Reorg_incourt[i]== 0.0) #zero se a observação não for de reorganização dentro da corte
        if12[i] = zero(0.0)
        
        #X e Y são as observações para toda a base de dados
        #x e y são as observações somente para os casos reorganizados dentro da corte
    else
        if12[i] = ( (X[i] - mean(x)) / var(x) ) * (  (Y[i] - mean(y)) - mm12 * (X[i] - mean(x)))
    end
end

mean(if12)

1.4903903027543768e-15

## Empilhando as funções influência

In [61]:
IF = hcat(if1, if2, if3, if4, if5, if6, if7, if8, if9, if10, if11, if12)

66×12 Array{Float64,2}:
  0.182388    0.15625   0.226668    0.030303   0.0         0.0        -0.284837    -0.0551954  -0.0404486   -0.0337907   -0.118289   -0.0583313
  0.0         0.15625  -0.888893    0.030303   0.246725    0.255734    0.134235     0.314281    0.0384389    0.0644288    0.620464   -2.40861
  0.0         0.15625   0.333373    0.030303   0.0         0.0        -0.0243292   -0.130289   -0.0230976   -0.0203689   -0.0585305  -0.471129
  0.121763    0.15625  -0.527103    0.030303  -0.0301013  -0.0210922   0.215077     0.0374548  -0.0463147   -0.0348091    0.10817    -0.376481
  0.441515    0.15625   0.485795    0.030303   0.0         0.0        -0.269891    -0.0317975  -0.0435503   -0.0356683    0.0663293   0.0491721
  0.0360496   0.15625   0.0803303   0.030303   0.0         0.0        -0.164161    -0.0561256  -0.046267    -0.0269051   -0.163215   -0.0311063
  1.18524     0.15625   0.536375    0.030303   0.0         0.0         0.216455     0.317188    0.0401424    0.06628

In [62]:
n = nrow(df);

In [63]:
n^2

4356

In [64]:
W = 1/(n^2) * transpose(IF) * IF

12×12 Array{Float64,2}:
  0.00597747   -0.000437554   0.00114374   -2.03325e-19  -7.93767e-5   -7.76837e-5   -5.31024e-5   -4.01707e-5    1.03767e-5   -4.72152e-5   7.48986e-5    0.000204162
 -0.000437554   0.00193698   -0.000892831  -1.1117e-20   -4.18274e-6   -4.51023e-8   -7.35587e-20  -1.60918e-20  -1.66903e-6   -1.3084e-6   -0.000100003   3.50139e-18
  0.00114374   -0.000892831   0.00245387    1.12634e-19   4.89032e-6   -9.84647e-6   -0.000158145  -0.000178559  -4.35126e-5   -7.1445e-5    0.000259951  -0.000319197
 -2.0073e-19   -9.79382e-21   1.14328e-19   0.000445224  -2.67695e-5   -2.88655e-7   -1.18291e-20  -7.81986e-21  -3.2369e-7    -2.53751e-7  -1.18031e-6    6.84841e-19
 -7.93767e-5   -4.18274e-6    4.89032e-6   -2.67695e-5    0.000201237   0.00018711    6.51706e-5    0.00016561    1.27064e-5    1.37164e-5   1.07336e-5   -0.00100433
 -7.76837e-5   -4.51023e-8   -9.84647e-6   -2.88655e-7    0.00018711    0.000200397   6.39179e-5    0.000171447   7.1489e-6     1.67941e-5   1

In [65]:
omega = inv(W)

12×12 Array{Float64,2}:
  190.122       1.9209     -91.4061     16.4573       275.781      -123.423    -32.0216    -60.7386    -438.515      427.381     11.6689     4.66635
    1.9209    640.403      268.819       0.738542       7.25325    -158.051     72.029      94.5374     -75.6685     873.97     -14.4069     1.56581
  -91.4061    268.819      651.853     -21.8514      -370.491      -102.501    150.365     251.935      102.099     1765.53    -222.268     -9.1413
   16.4573      0.738542   -21.8514   2414.24        2826.9       -2460.51     -80.1266    -30.1728   -1072.59       899.49      26.3921    31.0836
  275.781       7.25325   -370.491    2826.9        47525.7      -41445.2    -1381.46     -445.722   -18279.9      14935.2      382.154    520.286
 -123.423    -158.051     -102.501   -2460.51      -41445.2       48674.6      693.686   -2064.34     15465.7     -20500.8      115.475    460.924
  -32.0216     72.029      150.365     -80.1266     -1381.46        693.686   1942.23   

In [66]:
diag(omega)

12-element Array{Float64,1}:
   190.12235655936541
   640.4031885434607
   651.8528619215795
  2414.2400168746167
 47525.699618958846
 48674.59883071847
  1942.2252967011827
  3623.0223577869415
 54580.67577873802
 85610.59913599025
  1662.8059838431564
   183.71272006150195

Versão da matriz de ponderação sem os momentos com função influência problemática

Isto é, sem ussar momentos baseados em variância

In [82]:
IF = hcat(if1, if2, if3, if4, if5, if6, if7, if8, if12)

n = nrow(df);

n^2

W = 1/(n^2) * transpose(IF) * IF

omega = inv(W)

diag(omega)

9-element Array{Float64,1}:
   186.27865565012843
   628.2143871732253
   574.6134577730481
  2392.458925860092
 41266.6613397589
 42801.47971991768
  1645.4199267096578
  3465.235248992827
   158.94622655520953

### Clusterizando por ano?

In [91]:
Years = df.processo[:];

for i in 1:length(Years)
    Years[i] = df.processo[i][12:15]
end

In [92]:
Unique_Years = sort(unique(Years))

10-element Array{Any,1}:
 "2008"
 "2009"
 "2010"
 "2011"
 "2012"
 "2013"
 "2014"
 "2015"
 "2016"
 "2017"

In [93]:
#cada linha da IFCluster representa um ano, e cada coluna representa um momento
IFCluster = zeros(length(Unique_Years), size(IF,2));

for (t, year) in enumerate(Unique_Years)
    for i in 1:nrow(df)
        if(Years[i]==year)
            IFCluster[t,:] += IF[i, :]
        end
    end
end



In [94]:
IFCluster

10×9 Array{Float64,2}:
 -1.25032    0.625    -1.37485    0.121212    0.155478    0.173496     0.510738   0.88387    -2.02394
 -2.56323    0.46875  -0.415483   0.0909091  -0.187541   -0.178532     0.410883   0.0200869   0.258836
  0.605189   0.3125   -0.692544   0.0606061  -0.0301013  -0.0210922    0.31021    0.345991   -0.495282
 -0.678731   0.46875  -0.856524   0.0909091   0.246725    0.255734     0.343709   0.199833   -2.49574
  2.83473   -0.59375   0.794798   0.272727    0.161015    0.170024    -0.236075   0.148841    1.79275
 -0.111826   1.5       0.57815    0.484848   -0.123803    0.118739     0.585784   0.0571613   0.535777
  0.731384  -0.8125    1.98256    0.424242   -0.248848   -0.22182     -1.47228   -0.999476   -0.486964
  0.316321   0.625    -0.928733   0.121212    0.295652    0.075695     0.648411  -0.177633   -0.569087
  0.116487  -1.75      0.542184   0.242424   -0.385184   -0.3735      -1.10138   -0.478675    3.48365
  0.0       -0.84375   0.370441  -1.90909     0.116608

In [95]:
W2 = 1/(n) * transpose(IFCluster) * IFCluster

9×9 Array{Float64,2}:
  0.267532    -0.0691403   0.0962726    0.0103963     0.00662972   0.00517038   -0.0526065   -0.0228829    0.12353
 -0.0691403    0.126598   -0.0716563    0.0251951     0.0120736    0.0165953     0.0805699    0.0348444   -0.133113
  0.0962726   -0.0716563   0.14343      0.00493282   -0.0182349   -0.0132897    -0.0810504   -0.0539249    0.126398
  0.0103963    0.0251951   0.00493282   0.0642792    -0.00574908  -0.000714637  -0.00672832  -0.00523013   0.0127114
  0.00662972   0.0120736  -0.0182349   -0.00574908    0.00717691   0.00543114    0.0143878    0.00863652  -0.0322828
  0.00517038   0.0165953  -0.0132897   -0.000714637   0.00543114   0.0055343     0.0138342    0.00928341  -0.0286807
 -0.0526065    0.0805699  -0.0810504   -0.00672832    0.0143878    0.0138342     0.0733939    0.038145    -0.083895
 -0.0228829    0.0348444  -0.0539249   -0.00523013    0.00863652   0.00928341    0.038145     0.0337322   -0.0490315
  0.12353     -0.133113    0.126398     0.01271

In [97]:
omega2 = inv(W2)

9×9 Array{Float64,2}:
   19.4896     -30.4884    -8.98264     1.63859   -173.787      34.0241     61.5192   -25.5541   -14.9479
  -30.4884     951.794   -334.452    -413.2       1354.99     -370.029   -1502.91     188.955    231.92
   -8.98264   -334.452    226.288     192.09       -16.5313   -401.856     568.213     78.01     -86.1266
    1.63859   -413.2      192.09      220.789     -321.275    -116.302     664.127    -13.9442  -100.752
 -173.787     1354.99     -16.5313   -321.275     4768.13    -3246.91    -2061.67     913.059    345.846
   34.0241    -370.029   -401.856    -116.302    -3246.91     4250.22      276.055   -928.9      -15.9671
   61.5192   -1502.91     568.213     664.127    -2061.67      276.055    2455.84    -269.274   -378.09
  -25.5541     188.955     78.01      -13.9442     913.059    -928.9      -269.274    317.686     35.5304
  -14.9479     231.92     -86.1266   -100.752      345.846     -15.9671   -378.09      35.5304    65.4565

In [98]:
diag(omega2)

9-element Array{Float64,1}:
   19.489597497742135
  951.7940020231325
  226.28836355813746
  220.78885545476547
 4768.1330364744945
 4250.222685166682
 2455.8378533393666
  317.68567875241894
   65.45653404370154

In [99]:
using DelimitedFiles

writedlm( "WCluster.csv",  omega2, ',')

In [100]:
WCluster = readdlm("WCluster.csv", ',')

9×9 Array{Float64,2}:
   19.4896     -30.4884    -8.98264     1.63859   -173.787      34.0241     61.5192   -25.5541   -14.9479
  -30.4884     951.794   -334.452    -413.2       1354.99     -370.029   -1502.91     188.955    231.92
   -8.98264   -334.452    226.288     192.09       -16.5313   -401.856     568.213     78.01     -86.1266
    1.63859   -413.2      192.09      220.789     -321.275    -116.302     664.127    -13.9442  -100.752
 -173.787     1354.99     -16.5313   -321.275     4768.13    -3246.91    -2061.67     913.059    345.846
   34.0241    -370.029   -401.856    -116.302    -3246.91     4250.22      276.055   -928.9      -15.9671
   61.5192   -1502.91     568.213     664.127    -2061.67      276.055    2455.84    -269.274   -378.09
  -25.5541     188.955     78.01      -13.9442     913.059    -928.9      -269.274    317.686     35.5304
  -14.9479     231.92     -86.1266   -100.752      345.846     -15.9671   -378.09      35.5304    65.4565

In [102]:
diag(WCluster)

9-element Array{Float64,1}:
   19.489597497742135
  951.7940020231325
  226.28836355813746
  220.78885545476547
 4768.1330364744945
 4250.222685166682
 2455.8378533393666
  317.68567875241894
   65.45653404370154