A ideia é mudar o rand() por uma outra função que busque o valor dos draws da uniforme de um vetor já determinado

In [1]:
U = rand(10, 2)

10×2 Array{Float64,2}:
 0.00596311  0.362791
 0.663348    0.220862
 0.121389    0.293119
 0.870124    0.272928
 0.623652    0.410207
 0.635308    0.272175
 0.52683     0.6873
 0.460969    0.973913
 0.179934    0.433254
 0.380041    0.0885041

In [2]:
draw = [1]

1-element Array{Int64,1}:
 1

In [3]:
draw[1] += 1

2

In [4]:
draw

1-element Array{Int64,1}:
 2

In [6]:
U1 = U[:,1]
U1[draw]

1-element Array{Float64,1}:
 0.6633484589169714

In [7]:
draw = [1] #precisa criar um vetor unitário para que o índice seja mutável

function rand_fixo!(U, draw)
    #tira um draw do U pré-determinado
    #atualiza o índice i para que o próximo draw seja num índice diferente
    
    
    u = U[draw]
    
    draw[1] += 1
    
    return u[1]
end
    

rand_fixo! (generic function with 1 method)

In [8]:
S = 100
N = 66
ndraws = 120

U = rand(S, N, ndraws)

100×66×120 Array{Float64,3}:
[:, :, 1] =
 0.587713  0.905404   0.441222  0.422047   …  0.0301264  0.0773567  0.74348
 0.134648  0.417063   0.378981  0.295204      0.25307    0.0587712  0.0253831
 0.786811  0.321177   0.567831  0.576615      0.11631    0.117372   0.668664
 0.692179  0.401906   0.479992  0.375439      0.312227   0.613682   0.282613
 0.880088  0.0336193  0.478246  0.165326      0.630142   0.179522   0.571648
 0.488797  0.792087   0.468918  0.206901   …  0.0743541  0.706778   0.348688
 0.581712  0.822138   0.542739  0.267812      0.542132   0.503112   0.623096
 0.733678  0.733304   0.598773  0.847259      0.438463   0.368      0.511921
 0.413956  0.43651    0.472711  0.142084      0.742392   0.526542   0.6141
 0.225043  0.361889   0.177011  0.369064      0.530965   0.140139   0.706521
 0.589615  0.276172   0.805439  0.622353   …  0.308451   0.830754   0.544538
 0.771583  0.385019   0.462859  0.702504      0.116468   0.830981   0.124729
 0.245891  0.321098   0.378388  0.477

In [120]:
#testando a parte de escrever o arquivo no computador

# using DelimitedFiles

# writedlm( "Uteste.csv",  U, ',')

# U2 = readdlm("Uteste.csv", ',')

# U2 = reshape(U2, (S,N,120))

# U2 == U

In [9]:


@show u = rand_fixo!(U[1,1,:], draw)

u = rand_fixo!(U[1, 1, :], draw) = 0.5877134213183886


0.5877134213183886

In [15]:
@show u = rand_fixo!(U[1,1,:], draw)
@show u = rand_fixo!(U[1,1,:], draw)

u = rand_fixo!(U[1, 1, :], draw) = 0.8494137751585307
u = rand_fixo!(U[1, 1, :], draw) = 0.7873422712572014


0.7873422712572014

In [25]:
function draw_rand!(U, draw)
    
    u = U[draw]
    
    draw[1] += 1
    
    return u[1]
    
end

draw_rand! (generic function with 1 method)

In [26]:
function simulate(U)
    
    
    draw = [1]
    
    for i in 1:5
        @show rand_fixo!(U, draw)
        @show draw
        
        @show draw_rand!(U, draw)
        @show draw
        
        @show draw_rand!(U, draw)
        @show draw
    end
    
    
end

simulate (generic function with 1 method)

In [27]:
U[1,1,:][1:20]

20-element Array{Float64,1}:
 0.5877134213183886
 0.31572257854670527
 0.11759443702022931
 0.6922612668525696
 0.6494054256126391
 0.6638790892042103
 0.906132636728644
 0.2803309098978708
 0.029115804198020845
 0.38895944479713007
 0.8864801970989704
 0.8494137751585307
 0.7873422712572014
 0.14993871346868382
 0.21461983261113815
 0.21540489976027488
 0.31622641944865104
 0.40663919652867664
 0.8683814169082527
 0.3394050415645302

In [28]:
simulate(U[1,1,:])

rand_fixo!(U, draw) = 0.5877134213183886
draw = [2]
draw_rand!(U, draw) = 0.31572257854670527
draw = [3]
draw_rand!(U, draw) = 0.11759443702022931
draw = [4]
rand_fixo!(U, draw) = 0.6922612668525696
draw = [5]
draw_rand!(U, draw) = 0.6494054256126391
draw = [6]
draw_rand!(U, draw) = 0.6638790892042103
draw = [7]
rand_fixo!(U, draw) = 0.906132636728644
draw = [8]
draw_rand!(U, draw) = 0.2803309098978708
draw = [9]
draw_rand!(U, draw) = 0.029115804198020845
draw = [10]
rand_fixo!(U, draw) = 0.38895944479713007
draw = [11]
draw_rand!(U, draw) = 0.8864801970989704
draw = [12]
draw_rand!(U, draw) = 0.8494137751585307
draw = [13]
rand_fixo!(U, draw) = 0.7873422712572014
draw = [14]
draw_rand!(U, draw) = 0.14993871346868382
draw = [15]
draw_rand!(U, draw) = 0.21461983261113815
draw = [16]


In [31]:
U[1,1,:]

120-element Array{Float64,1}:
 0.020096248365889746
 0.23682396023154584
 0.345464298860106
 0.581448718038041
 0.8631764960285797
 0.2773397738779031
 0.22711312925210625
 0.3147430863744167
 0.48081928996056433
 0.8694364975097131
 0.2792952394380015
 0.41548925328317443
 0.4977394852260808
 ⋮
 0.3364565399438477
 0.5146813799901553
 0.015257852963698415
 0.3351396897371508
 0.8432161235544584
 0.8037441417612781
 0.9977061743478881
 0.8361459611890065
 0.23015894681156213
 0.3525134722370491
 0.01577026372240886
 0.606604367637523