A ideia é mudar o rand() por uma outra função que busque o valor dos draws da uniforme de um vetor já determinado

In [38]:
U = rand(10, 2)

10×2 Array{Float64,2}:
 0.704859  0.102519
 0.976737  0.293896
 0.77863   0.825114
 0.557969  0.0223169
 0.716483  0.606953
 0.886165  0.304711
 0.221123  0.56009
 0.307695  0.16526
 0.344674  0.339987
 0.600914  0.759306

In [82]:
draw = [1]

1-element Array{Int64,1}:
 1

In [83]:
draw[1] += 1

2

In [81]:
draw

1-element Array{Int64,1}:
 2

In [75]:
U1[draw]

1-element Array{Float64,1}:
 0.9767368766925306

In [106]:
draw = [1] #precisa criar um vetor unitário para que o índice seja mutável

function rand_fixo!(U, draw)
    #tira um draw do U pré-determinado
    #atualiza o índice i para que o próximo draw seja num índice diferente
    
    
    u = U[draw]
    
    draw[1] += 1
    
    return u[1]
end
    

rand_fixo! (generic function with 1 method)

In [107]:
S = 100
N = 66
ndraws = 120

U = rand(S, N, ndraws)

100×66×120 Array{Float64,3}:
[:, :, 1] =
 0.098012   0.073498   0.195509   …  0.123909   0.798237   0.781531
 0.892919   0.185734   0.177518      0.256547   0.926421   0.58014
 0.270568   0.370257   0.955138      0.27195    0.747195   0.358753
 0.295818   0.837621   0.166693      0.148704   0.331745   0.72977
 0.769308   0.244431   0.773517      0.788984   0.266155   0.331959
 0.0541687  0.38127    0.455933   …  0.571593   0.383557   0.880702
 0.880577   0.282222   0.830887      0.546806   0.25251    0.635653
 0.0467339  0.0427883  0.706824      0.453718   0.0631076  0.743165
 0.147095   0.579565   0.329076      0.716379   0.186315   0.6471
 0.780677   0.612336   0.706352      0.656227   0.972259   0.221192
 0.140075   0.223383   0.296288   …  0.996521   0.851733   0.929523
 0.932533   0.619488   0.501019      0.752171   0.857827   0.13574
 0.179319   0.985742   0.569762      0.389824   0.834435   0.456532
 ⋮                                ⋱                        ⋮
 0.508063   0.54342

In [120]:
using DelimitedFiles

writedlm( "U.csv",  U, ',')

In [121]:
U2 = readdlm("U.csv", ',')



792000×1 Array{Float64,2}:
 0.09801199640604041
 0.892918551158971
 0.2705683452071983
 0.2958182972442833
 0.769308211440155
 0.05416871821783675
 0.8805769122001879
 0.046733912574462355
 0.14709510707058837
 0.7806766382130788
 0.14007458336923917
 0.9325331686428151
 0.17931937232645678
 ⋮
 0.6285236288126876
 0.8786076487398145
 0.0633697909918216
 0.8671987591612527
 0.8306850274370949
 0.37328297944514577
 0.061783638436904154
 0.6253230186489929
 0.5709988463230071
 0.7626231487190902
 0.9098879660067711
 0.7104555013516736

In [122]:
U2 = reshape(U2, (S, N, 120))

100×66×120 Array{Float64,3}:
[:, :, 1] =
 0.098012   0.073498   0.195509   …  0.123909   0.798237   0.781531
 0.892919   0.185734   0.177518      0.256547   0.926421   0.58014
 0.270568   0.370257   0.955138      0.27195    0.747195   0.358753
 0.295818   0.837621   0.166693      0.148704   0.331745   0.72977
 0.769308   0.244431   0.773517      0.788984   0.266155   0.331959
 0.0541687  0.38127    0.455933   …  0.571593   0.383557   0.880702
 0.880577   0.282222   0.830887      0.546806   0.25251    0.635653
 0.0467339  0.0427883  0.706824      0.453718   0.0631076  0.743165
 0.147095   0.579565   0.329076      0.716379   0.186315   0.6471
 0.780677   0.612336   0.706352      0.656227   0.972259   0.221192
 0.140075   0.223383   0.296288   …  0.996521   0.851733   0.929523
 0.932533   0.619488   0.501019      0.752171   0.857827   0.13574
 0.179319   0.985742   0.569762      0.389824   0.834435   0.456532
 ⋮                                ⋱                        ⋮
 0.508063   0.54342

In [125]:
U2 == U

true

In [119]:


@show u = rand_fixo!(U[1,1,:], draw)

u = rand_fixo!(U[1, 1, :], draw) = 0.968381177613145


0.968381177613145

In [89]:
@show u = rand_fixo!(U1, draw)
@show u = rand_fixo!(U1, draw)

u = rand_fixo!(U1, draw) = [0.8861649132104761]
u = rand_fixo!(U1, draw) = [0.22112339109920676]


1-element Array{Float64,1}:
 0.22112339109920676

In [48]:
@show u = rand_fixo!(U1, draw)
@show u = rand_fixo!(U1, i)
@show u = rand_fixo!(U1, i)
@show u = rand_fixo!(U1, i)
@show u = rand_fixo!(U1, i)

u = rand_fixo!(U1, i) = 0.7048588304794106
u = rand_fixo!(U1, i) = 0.7048588304794106
u = rand_fixo!(U1, i) = 0.7048588304794106
u = rand_fixo!(U1, i) = 0.7048588304794106
u = rand_fixo!(U1, i) = 0.7048588304794106


0.7048588304794106

In [51]:
draw = 1


1

In [55]:
draw = draw +1

3

In [56]:
draw

3

In [90]:
function simulate(U)
    
    
    draw = [1]
    
    for i in 1:10
        @show rand_fixo!(U1, draw)
        @show draw
    end
    
    
end

simulate (generic function with 1 method)

In [91]:
simulate(U1)

rand_fixo!(U1, draw) = [0.7048588304794106]
draw = [2]
rand_fixo!(U1, draw) = [0.9767368766925306]
draw = [3]
rand_fixo!(U1, draw) = [0.7786295020326373]
draw = [4]
rand_fixo!(U1, draw) = [0.557968508834775]
draw = [5]
rand_fixo!(U1, draw) = [0.7164834059234435]
draw = [6]
rand_fixo!(U1, draw) = [0.8861649132104761]
draw = [7]
rand_fixo!(U1, draw) = [0.22112339109920676]
draw = [8]
rand_fixo!(U1, draw) = [0.30769471348689836]
draw = [9]
rand_fixo!(U1, draw) = [0.3446738691470579]
draw = [10]
rand_fixo!(U1, draw) = [0.6009139535208861]
draw = [11]


In [31]:
U[1,1,:]

120-element Array{Float64,1}:
 0.020096248365889746
 0.23682396023154584
 0.345464298860106
 0.581448718038041
 0.8631764960285797
 0.2773397738779031
 0.22711312925210625
 0.3147430863744167
 0.48081928996056433
 0.8694364975097131
 0.2792952394380015
 0.41548925328317443
 0.4977394852260808
 ⋮
 0.3364565399438477
 0.5146813799901553
 0.015257852963698415
 0.3351396897371508
 0.8432161235544584
 0.8037441417612781
 0.9977061743478881
 0.8361459611890065
 0.23015894681156213
 0.3525134722370491
 0.01577026372240886
 0.606604367637523